---
title: "Interactive Plots"
author: "Tyler Hill"
date: "3/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/home/tyler/School/INSH5302/MyCity")
```

***

```{r, warning=F, message=F}
# Load libraries
library(tidyverse)
library(leaflet)
library(sf)
library(htmltools)
library(tigris)

# Load in the data
data_f <- file.path(".", "data.RData")
load(data_f)
```

# Terry Stop Map

I will work with data only from 2018 just to get the map working. I will filter the df in the subsequent shiny app with a slider so the user can select the year they want to see data for.

```{r}
# Subset the data for 2018
terry_2018 <- terry_df %>% 
  filter(Year == 2018)

beat_stops <- terry_2018 %>% 
  group_by(Beat) %>% 
  summarise(total_stops = n())

# Add missing beats data to beats_stops
dif_beats <- setdiff(beats$beat, beat_stops$Beat)
for (b in dif_beats) {
  beat_stops <- beat_stops %>% 
    add_row(Beat = b, total_stops = 0)
}

# Combine terry stop data into the shapefile
beats <- geo_join(beats, beat_stops, "beat", "Beat")

# Set chloropleth color palette
bins <- c(0, 20, 50, 90, 140, 200, 270, Inf)
pal <- colorBin("YlGnBu", domain = beats$total_stops, bins = bins)

beat_info <- paste(
    "Beat: ", beats$beat,"<br/>",
    "Terry Stops: ", beats$total_stops, "<br/>",
    sep="") %>%
  lapply(htmltools::HTML)

terry_map <- leaflet(options = leafletOptions(minZoom = 10)) %>% 
  addTiles() %>% 
  addPolygons(data = beats,
              stroke = 1,
              weight = 1,
              color = "grey",
              fillColor = ~pal(total_stops),
              fillOpacity = 0.5,
              label = beat_info,
              highlight = highlightOptions(
                weight = 3,
                color = "#666",
                fillOpacity = 0.6,
                bringToFront = TRUE)) %>%
  addLegend(pal = pal,
            values = beats$total_stops,
            opacity = 0.6,
            title = NULL,
            position = "bottomright") %>% 
  setView((-122.4597 + -122.2244)/2, (47.48173+47.74913)/2, 10) %>% 
  setMaxBounds(-122.4597, 47.74913,  -122.2244, 47.48173)

terry_map
```

